/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    B2: typeof import('./src/components/layout/playbar/b2.vue')['default']
    Backend: typeof import('./src/components/layout/playbar/backend.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Header: typeof import('./src/components/layout/header/Header.vue')['default']
    Index: typeof import('./src/components/layout/Index.vue')['default']
    LangSwitcher: typeof import('./src/components/layout/header/LangSwitcher.vue')['default']
    Lyrics: typeof import('./src/components/layout/playbar/Lyrics.vue')['default']
    Main: typeof import('./src/components/layout/main/Main.vue')['default']
    PlayBar: typeof import('./src/components/layout/playbar/PlayBar.vue')['default']
    PlayerControls: typeof import('./src/components/layout/playbar/PlayerControls.vue')['default']
    PlaylistButton: typeof import('./src/components/layout/playbar/PlaylistButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/layout/sidebar/SideBar.vue')['default']
    SidebarItem: typeof import('./src/components/layout/sidebar/SidebarItem.vue')['default']
    SongItem: typeof import('./src/components/song/SongItem.vue')['default']
    SongMenuItem: typeof import('./src/components/song/SongMenuItem.vue')['default']
    TrackInfo: typeof import('./src/components/layout/playbar/TrackInfo.vue')['default']
    TrackRow: typeof import('./src/components/layout/playbar/TrackRow.vue')['default']
    Volume: typeof import('./src/components/layout/playbar/Volume.vue')['default']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
